### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by BlackIQ** [nguyenphuminh/HelloWorld#12]
See this and copy some others 👍🏻

https://github.com/BlackIQ/Hello-World

**Comment by nguyenphuminh** [comment]
Thanks, I will check it out!

**Comment by BlackIQ** [comment]
Look at README and Python file that generates README.
It is useful.

**Comment by nguyenphuminh** [comment]
Btw, I have created this programming language called "FreakC", it would be nice if you check it out: https://github.com/FreakC-Foundation/FreakC 😄
